// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BlogPost.tsx";
import * as $$$$$$1 from "./sections/BlogPosts.tsx";
import * as $$$$$$2 from "./sections/DoubleCard.tsx";
import * as $$$$$$3 from "./sections/Faq.tsx";
import * as $$$$$$4 from "./sections/Footer.tsx";
import * as $$$$$$5 from "./sections/Header.tsx";
import * as $$$$$$6 from "./sections/Hero.tsx";
import * as $$$$$$7 from "./sections/Highlight.tsx";
import * as $$$$$$8 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$9 from "./sections/Logos.tsx";
import * as $$$$$$10 from "./sections/MainPost.tsx";
import * as $$$$$$14 from "./sections/mymaintest.tsx";
import * as $$$$$$11 from "./sections/OurInvestment.tsx";
import * as $$$$$$12 from "./sections/Testimonials.tsx";
import * as $$$$$$13 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/BlogPost.tsx": $$$$$$0,
    "site/sections/BlogPosts.tsx": $$$$$$1,
    "site/sections/DoubleCard.tsx": $$$$$$2,
    "site/sections/Faq.tsx": $$$$$$3,
    "site/sections/Footer.tsx": $$$$$$4,
    "site/sections/Header.tsx": $$$$$$5,
    "site/sections/Hero.tsx": $$$$$$6,
    "site/sections/Highlight.tsx": $$$$$$7,
    "site/sections/ImageWithParagraph.tsx": $$$$$$8,
    "site/sections/Logos.tsx": $$$$$$9,
    "site/sections/MainPost.tsx": $$$$$$10,
    "site/sections/mymaintest.tsx": $$$$$$14,
    "site/sections/OurInvestment.tsx": $$$$$$11,
    "site/sections/Testimonials.tsx": $$$$$$12,
    "site/sections/Theme/Theme.tsx": $$$$$$13,
  },
  "apps": {
    "site/apps/decohub.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
